### PR TITLE
Add basic installation guide for early adopters

### PR DESCRIPTION
**Pull request by jmaxxz**

### CODE REVIEW

**Comment by emilyrose** [comment]
Hey @jmaxxz,

Awesome! I've been meaning to get to this but have been overwhelmed, so this is super helpful!

Two things:
* Could you please [sign our CLA](https://docs.google.com/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform)?
* Would you also like to add yourself to the collaborators list in `package.json`?

Thanks a ton! :smile_cat:

**Comment by jmaxxz** [comment]
@emilyrose I will not sign your CLA.  I have participated in a number of open source projects and never been asked for my home address. I have my changes are in compliance LGPL which this project is covered under. If the LGPL is too restrictive for Particle please select a less restrictive licence.

If your concern is particle's ability to change licenses in the future please add a contributor.md file to your repository stating some legal verbiage (that is readable to us devs) to that affect. https://github.com/blog/1184-contributing-guidelines

If you wish me to bear any liability for particle's code or its code base why would I ever do that.

As for the form asking me for my home address, personal phone number, full name, and email address is out of line. I would never ask you to provide me with yours, so what makes anyone at particle think you can ask for mine?

If your lawyers need more I am willing to say the following:
All my contributions to the project are my own work and are contributed under the [WTFPL](http://www.wtfpl.net/about/).

Keep up the great work, but please tell your lawyers to go back to the drawing board.

**Comment by zsup** [comment]
Hey @jmaxxz - thanks so much for the contribution but unfortunately we can't accept contributions without the CLA. I understand your concerns, but we're using the same CLA that Google uses, which is derived from the Apache CLA, so I feel like it's a pretty decent solution for us. That said, we can't force you to sign it, and I respect your concerns, so I'm going to go ahead and close the PR.

Thanks for your help regardless!

**Comment by jmaxxz** [comment]
@zsup remove the PII from the CLA and I will sign it but if PII is a must good like.

**Pull request closed without merging**
